"""Build the admin / structural variables block of variable_mapping_2022_2024.csv.

Session 05 Block D.

Maps: id, ctrcode, ctryear, year, weight. Same variable names in both waves
(verified in codebooks). Per Session 05 brief: analytic_name keeps the
original variable name (no iv_/dv_ prefix) so Script 04 can pass them through
transparently as structural metadata rather than analytic content.

5 rows. All clean. Notes spell out structural role for Script 04.

Source instrument: NEITHER Core nor Background - these are pre-treatment
metadata generated by the survey infrastructure (id, country code, weights,
date stamps). Documented in the OECD Technical Documentation Survey Design
PDF. Tagged [instrument: Metadata] (new tag value, distinct from Core/Bg).
"""

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / "data" / "processed" / "variable_mapping_2022_2024.csv"
INSTRUMENT_TAG = " [instrument: Metadata]"

# (analytic_name == var_name in both waves for admin), wording, vl, status, recode, notes
ROWS = [
    (
        "id", "id", "id",
        "(Survey-generated respondent ID; not asked as a question.)",
        "(Survey-generated respondent ID; not asked as a question.)",
        "(no value labels; float32 in both waves)",
        "(no value labels; float32 in both waves)",
        True, "clean", "No recoding required.",
        "ROLE: merge key. Unique per row within each wave; no cross-wave "
        "overlap expected. Script 04 uses this as the row identifier; combine "
        "with `year` for a stable pooled key.",
    ),
    (
        "ctrcode", "ctrcode", "ctrcode",
        "(Survey-generated; not asked as a question.)",
        "(Survey-generated; not asked as a question.)",
        "(ISO 3-letter country code stored as string; no value labels)",
        "(ISO 3-letter country code stored as string; no value labels)",
        True, "clean", "No recoding required.",
        "ROLE: country identifier and join key for country-level Level-2 "
        "variables (typology_positions.csv, EPL, PIAAC, etc.). Identical "
        "string format both waves. Use as the cluster identifier for any "
        "country-clustered standard errors.",
    ),
    (
        "ctryear", "ctryear", "ctryear",
        "(Survey-generated; not asked as a question.)",
        "(Survey-generated; not asked as a question.)",
        "(Country-year identifier stored as string; no value labels)",
        "(Country-year identifier stored as string; no value labels)",
        True, "clean", "No recoding required.",
        "ROLE: cluster identifier for country-wave random effects in the "
        "multilevel specification.",
    ),
    (
        "year", "year", "year",
        "(Survey-generated; not asked as a question.)",
        "(Survey-generated; not asked as a question.)",
        "(float32 in 2022 [no label], float32 in 2024 [label: 'Year']; values 2022 or 2024)",
        "(float32 with label 'Year'; values 2022 or 2024)",
        True, "clean", "No recoding required.",
        "ROLE: wave indicator. Becomes the wave fixed effect. Also use to "
        "construct the wave-by-AI-exposure interaction term per the v2 spec.",
    ),
    (
        "weight", "weight", "weight",
        "(Survey weight; constructed by the OECD post-collection.)",
        "(Survey weight; constructed by the OECD post-collection.)",
        "(float64, no value labels)",
        "(float64, no value labels)",
        True, "clean", "No recoding required at the per-row level.",
        "ROLE: survey weight. *** WEIGHT-CONSTRUCTION CAVEAT *** per v1 "
        "analytic list section 1: 'Confirm weight construction is comparable "
        "across waves. OECD may have changed raking variables.' "
        "Verify against OECD-RTM-Technical-Documentation-Survey-Design.pdf "
        "(2022) and the equivalent 2024 methodology before pooling weighted "
        "estimates. If raking variables differ, document and decide whether "
        "to (a) use unweighted models, (b) construct a common reweighting, or "
        "(c) report wave-stratified weighted estimates only.",
    ),
]

HEADER = [
    "analytic_name", "var_2022", "var_2024",
    "wording_2022", "wording_2024",
    "value_labels_2022", "value_labels_2024",
    "scale_compatible", "harmonization_status", "recode_rule",
    "notes", "verified_by_human",
]


def main() -> None:
    existing = []
    if OUT.exists():
        with OUT.open("r", encoding="utf-8", newline="") as f:
            existing = list(csv.DictReader(f))

    new_dicts = []
    for r in ROWS:
        d = dict(zip(HEADER[:-1], r))
        if "[instrument:" not in d["notes"]:
            d["notes"] = d["notes"].rstrip() + INSTRUMENT_TAG
        d["verified_by_human"] = "False"
        new_dicts.append(d)

    new_names = {d["analytic_name"] for d in new_dicts}
    kept = [row for row in existing if row.get("analytic_name") not in new_names]
    combined = kept + new_dicts

    with OUT.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=HEADER, quoting=csv.QUOTE_MINIMAL)
        w.writeheader()
        w.writerows(combined)

    print(
        f"Wrote {OUT} ({len(combined)} rows total: "
        f"{len(kept)} preserved + {len(new_dicts)} new)"
    )


if __name__ == "__main__":
    main()
